// Generated by `node scripts/shape/registers.mjs --profile` from the frozen human baselines.
// Do not edit by hand: rerun the script after adding or re-extracting a baseline.

import type { RegisterProfile } from "./check.js";

export const PROFILE_PARAGRAPHS = 5;
export const PROFILE_MEASURED = "2026-09-30";
export const PROFILE_SOURCES: Readonly<Record<string, string>> = {
  "business-email": "enron",
  "explanatory": "hc3-human",
  "institutional": "hansard-commons",
  "literary": "gutenberg",
  "marketing": "wayback-uk-sme"
};
export const PROFILE: RegisterProfile = {
  "business-email": {
    "clauseDepth": {
      "p10": 0.36,
      "p50": 0.673,
      "p90": 1.113,
      "sd": 0.307,
      "separates": [
        "explanatory",
        "institutional",
        "literary"
      ]
    },
    "commasPer100": {
      "p10": 1.424,
      "p50": 3.19,
      "p90": 5.154,
      "sd": 1.529,
      "separates": [
        "institutional",
        "literary"
      ]
    },
    "commasPerSentence": {
      "p10": 0.2,
      "p50": 0.467,
      "p90": 0.826,
      "sd": 0.262,
      "separates": [
        "explanatory",
        "institutional",
        "literary",
        "marketing"
      ]
    },
    "coordinationRate": {
      "p10": 0,
      "p50": 0.743,
      "p90": 1.712,
      "sd": 0.666,
      "separates": [
        "marketing"
      ]
    },
    "figures": {
      "p10": 0.2,
      "p50": 0.8,
      "p90": 1.8,
      "sd": 0.725,
      "separates": [
        "literary"
      ]
    },
    "firstPersonPer100": {
      "p10": 3.718,
      "p50": 5.968,
      "p90": 8.375,
      "sd": 1.825,
      "separates": [
        "explanatory"
      ]
    },
    "generic": {
      "p10": 0,
      "p50": 0,
      "p90": 0.2,
      "sd": 0.138,
      "separates": [
        "explanatory"
      ]
    },
    "hardPer100": {
      "p10": 4.289,
      "p50": 7.127,
      "p90": 11.308,
      "sd": 2.843,
      "separates": [
        "explanatory",
        "institutional",
        "literary"
      ]
    },
    "impersonalOpenerShare": {
      "p10": 0,
      "p50": 0,
      "p90": 0.067,
      "sd": 0.031,
      "separates": [
        "explanatory"
      ]
    },
    "meanSentenceWords": {
      "p10": 11.417,
      "p50": 14.25,
      "p90": 17.87,
      "sd": 2.656,
      "separates": [
        "explanatory",
        "literary"
      ]
    },
    "meanWordLength": {
      "p10": 3.858,
      "p50": 4.16,
      "p90": 4.459,
      "sd": 0.231,
      "separates": [
        "explanatory"
      ]
    },
    "names": {
      "p10": 1.2,
      "p50": 2.4,
      "p90": 3.6,
      "sd": 0.965,
      "separates": [
        "explanatory",
        "institutional"
      ]
    },
    "nominalisationRate": {
      "p10": 0.625,
      "p50": 1.93,
      "p90": 3.831,
      "sd": 1.264,
      "separates": [
        "institutional",
        "marketing"
      ]
    },
    "participialRate": {
      "p10": 0,
      "p50": 0,
      "p90": 0.05,
      "sd": 0.035,
      "separates": [
        "literary"
      ]
    },
    "pronounOpenerShare": {
      "p10": 0,
      "p50": 0.05,
      "p90": 0.15,
      "sd": 0.068,
      "separates": [
        "marketing"
      ]
    },
    "sentenceCv": {
      "p10": 0.344,
      "p50": 0.468,
      "p90": 0.6,
      "sd": 0.099,
      "separates": [
        "marketing"
      ]
    },
    "skeletonRepeat": {
      "p10": 0,
      "p50": 0.017,
      "p90": 0.063,
      "sd": 0.031,
      "separates": [
        "institutional"
      ]
    },
    "specificsPer100": {
      "p10": 4.22,
      "p50": 7.34,
      "p90": 11.46,
      "sd": 2.892,
      "separates": [
        "explanatory",
        "institutional",
        "literary"
      ]
    },
    "tradePer100": {
      "p10": 0,
      "p50": 0,
      "p90": 0.588,
      "sd": 0.287,
      "separates": [
        "marketing"
      ]
    },
    "tricolons": {
      "p10": 0,
      "p50": 0,
      "p90": 0.2,
      "sd": 0.142,
      "separates": [
        "institutional",
        "literary",
        "marketing"
      ]
    }
  },
  "explanatory": {
    "clauseDepth": {
      "p10": 0.78,
      "p50": 1.194,
      "p90": 1.733,
      "sd": 0.383,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "commasPer100": {
      "p10": 2.579,
      "p50": 4.164,
      "p90": 6.089,
      "sd": 1.423,
      "separates": [
        "literary"
      ]
    },
    "commasPerSentence": {
      "p10": 0.448,
      "p50": 0.77,
      "p90": 1.2,
      "sd": 0.309,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "coordinationRate": {
      "p10": 0.323,
      "p50": 0.973,
      "p90": 1.862,
      "sd": 0.612,
      "separates": [
        "marketing"
      ]
    },
    "figures": {
      "p10": 0,
      "p50": 0.4,
      "p90": 1.4,
      "sd": 0.631,
      "separates": [
        "literary"
      ]
    },
    "firstPersonPer100": {
      "p10": 0.27,
      "p50": 1.282,
      "p90": 3.114,
      "sd": 1.181,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "generic": {
      "p10": 0,
      "p50": 0.4,
      "p90": 0.6,
      "sd": 0.214,
      "separates": [
        "business-email",
        "institutional"
      ]
    },
    "hardPer100": {
      "p10": 0.988,
      "p50": 2.62,
      "p90": 5.171,
      "sd": 1.713,
      "separates": [
        "business-email",
        "institutional",
        "marketing"
      ]
    },
    "impersonalOpenerShare": {
      "p10": 0,
      "p50": 0.04,
      "p90": 0.14,
      "sd": 0.061,
      "separates": [
        "business-email"
      ]
    },
    "meanSentenceWords": {
      "p10": 14.973,
      "p50": 18.31,
      "p90": 22.533,
      "sd": 3.013,
      "separates": [
        "business-email"
      ]
    },
    "meanWordLength": {
      "p10": 4.207,
      "p50": 4.466,
      "p90": 4.752,
      "sd": 0.213,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "names": {
      "p10": 0.4,
      "p50": 1.2,
      "p90": 2.6,
      "sd": 0.941,
      "separates": [
        "business-email",
        "institutional"
      ]
    },
    "nominalisationRate": {
      "p10": 0.766,
      "p50": 1.823,
      "p90": 3.416,
      "sd": 1.061,
      "separates": [
        "institutional",
        "marketing"
      ]
    },
    "participialRate": {
      "p10": 0,
      "p50": 0,
      "p90": 0.1,
      "sd": 0.045,
      "separates": []
    },
    "pronounOpenerShare": {
      "p10": 0,
      "p50": 0.033,
      "p90": 0.124,
      "sd": 0.056,
      "separates": [
        "marketing"
      ]
    },
    "sentenceCv": {
      "p10": 0.337,
      "p50": 0.441,
      "p90": 0.57,
      "sd": 0.092,
      "separates": []
    },
    "skeletonRepeat": {
      "p10": 0.009,
      "p50": 0.039,
      "p90": 0.091,
      "sd": 0.036,
      "separates": []
    },
    "specificsPer100": {
      "p10": 1.04,
      "p50": 2.7,
      "p90": 5.36,
      "sd": 1.731,
      "separates": [
        "business-email",
        "institutional",
        "marketing"
      ]
    },
    "tradePer100": {
      "p10": 0,
      "p50": 0,
      "p90": 0.427,
      "sd": 0.216,
      "separates": [
        "marketing"
      ]
    },
    "tricolons": {
      "p10": 0,
      "p50": 0.2,
      "p90": 0.6,
      "sd": 0.222,
      "separates": []
    }
  },
  "institutional": {
    "clauseDepth": {
      "p10": 0.792,
      "p50": 1.233,
      "p90": 1.76,
      "sd": 0.377,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "commasPer100": {
      "p10": 3.03,
      "p50": 4.435,
      "p90": 5.941,
      "sd": 1.165,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "commasPerSentence": {
      "p10": 0.61,
      "p50": 0.96,
      "p90": 1.375,
      "sd": 0.307,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "coordinationRate": {
      "p10": 0.323,
      "p50": 0.949,
      "p90": 1.752,
      "sd": 0.559,
      "separates": [
        "marketing"
      ]
    },
    "figures": {
      "p10": 0,
      "p50": 0.6,
      "p90": 1.4,
      "sd": 0.56,
      "separates": [
        "literary"
      ]
    },
    "generic": {
      "p10": 0,
      "p50": 0,
      "p90": 0.2,
      "sd": 0.114,
      "separates": [
        "explanatory",
        "literary",
        "marketing"
      ]
    },
    "hardPer100": {
      "p10": 3.41,
      "p50": 5.135,
      "p90": 7.304,
      "sd": 1.573,
      "separates": [
        "business-email",
        "explanatory",
        "literary"
      ]
    },
    "impersonalOpenerShare": {
      "p10": 0,
      "p50": 0.033,
      "p90": 0.109,
      "sd": 0.051,
      "separates": []
    },
    "names": {
      "p10": 2,
      "p50": 3.2,
      "p90": 4.8,
      "sd": 1.113,
      "separates": [
        "business-email",
        "explanatory",
        "literary",
        "marketing"
      ]
    },
    "nominalisationRate": {
      "p10": 1.992,
      "p50": 3.391,
      "p90": 5.008,
      "sd": 1.147,
      "separates": [
        "business-email",
        "explanatory",
        "literary"
      ]
    },
    "participialRate": {
      "p10": 0,
      "p50": 0,
      "p90": 0.1,
      "sd": 0.044,
      "separates": [
        "literary"
      ]
    },
    "pronounOpenerShare": {
      "p10": 0,
      "p50": 0.05,
      "p90": 0.164,
      "sd": 0.068,
      "separates": [
        "marketing"
      ]
    },
    "sentenceCv": {
      "p10": 0.386,
      "p50": 0.512,
      "p90": 0.639,
      "sd": 0.097,
      "separates": [
        "marketing"
      ]
    },
    "skeletonRepeat": {
      "p10": 0.018,
      "p50": 0.048,
      "p90": 0.087,
      "sd": 0.028,
      "separates": [
        "business-email"
      ]
    },
    "specificsPer100": {
      "p10": 3.36,
      "p50": 5.2,
      "p90": 7.4,
      "sd": 1.612,
      "separates": [
        "business-email",
        "explanatory",
        "literary"
      ]
    },
    "tradePer100": {
      "p10": 0,
      "p50": 0,
      "p90": 0.157,
      "sd": 0.101,
      "separates": [
        "marketing"
      ]
    },
    "tricolons": {
      "p10": 0,
      "p50": 0.2,
      "p90": 0.6,
      "sd": 0.233,
      "separates": [
        "business-email"
      ]
    }
  },
  "literary": {
    "clauseDepth": {
      "p10": 1.333,
      "p50": 2.017,
      "p90": 2.933,
      "sd": 0.626,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "marketing"
      ]
    },
    "commasPer100": {
      "p10": 5.997,
      "p50": 8.1,
      "p90": 10.586,
      "sd": 1.815,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "marketing"
      ]
    },
    "commasPerSentence": {
      "p10": 1.067,
      "p50": 1.667,
      "p90": 2.435,
      "sd": 0.541,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "marketing"
      ]
    },
    "coordinationRate": {
      "p10": 0.194,
      "p50": 0.814,
      "p90": 1.633,
      "sd": 0.572,
      "separates": [
        "marketing"
      ]
    },
    "figures": {
      "p10": 0,
      "p50": 0,
      "p90": 0,
      "sd": 0.079,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "marketing"
      ]
    },
    "firstPersonPer100": {
      "p10": 2.207,
      "p50": 4.67,
      "p90": 7.486,
      "sd": 2.027,
      "separates": [
        "explanatory"
      ]
    },
    "generic": {
      "p10": 0,
      "p50": 0.2,
      "p90": 0.4,
      "sd": 0.178,
      "separates": [
        "institutional"
      ]
    },
    "hardPer100": {
      "p10": 1.632,
      "p50": 3.076,
      "p90": 5.154,
      "sd": 1.367,
      "separates": [
        "business-email",
        "institutional"
      ]
    },
    "impersonalOpenerShare": {
      "p10": 0,
      "p50": 0,
      "p90": 0.067,
      "sd": 0.039,
      "separates": []
    },
    "meanSentenceWords": {
      "p10": 15.083,
      "p50": 20.35,
      "p90": 27.027,
      "sd": 4.744,
      "separates": [
        "business-email"
      ]
    },
    "meanWordLength": {
      "p10": 3.958,
      "p50": 4.186,
      "p90": 4.409,
      "sd": 0.175,
      "separates": [
        "explanatory"
      ]
    },
    "names": {
      "p10": 1,
      "p50": 1.8,
      "p90": 3,
      "sd": 0.816,
      "separates": [
        "institutional"
      ]
    },
    "nominalisationRate": {
      "p10": 0.444,
      "p50": 1.334,
      "p90": 2.486,
      "sd": 0.817,
      "separates": [
        "institutional",
        "marketing"
      ]
    },
    "participialRate": {
      "p10": 0,
      "p50": 0.067,
      "p90": 0.2,
      "sd": 0.089,
      "separates": [
        "business-email",
        "institutional"
      ]
    },
    "pronounOpenerShare": {
      "p10": 0,
      "p50": 0.025,
      "p90": 0.12,
      "sd": 0.058,
      "separates": [
        "marketing"
      ]
    },
    "sentenceCv": {
      "p10": 0.367,
      "p50": 0.485,
      "p90": 0.625,
      "sd": 0.1,
      "separates": [
        "marketing"
      ]
    },
    "skeletonRepeat": {
      "p10": 0.005,
      "p50": 0.029,
      "p90": 0.07,
      "sd": 0.028,
      "separates": []
    },
    "specificsPer100": {
      "p10": 1.8,
      "p50": 3.28,
      "p90": 5.24,
      "sd": 1.365,
      "separates": [
        "business-email",
        "institutional",
        "marketing"
      ]
    },
    "tradePer100": {
      "p10": 0,
      "p50": 0,
      "p90": 0.508,
      "sd": 0.275,
      "separates": [
        "marketing"
      ]
    },
    "tricolons": {
      "p10": 0,
      "p50": 0.4,
      "p90": 0.8,
      "sd": 0.314,
      "separates": [
        "business-email"
      ]
    }
  },
  "marketing": {
    "clauseDepth": {
      "p10": 0.567,
      "p50": 0.967,
      "p90": 1.56,
      "sd": 0.413,
      "separates": [
        "literary"
      ]
    },
    "commasPer100": {
      "p10": 2.169,
      "p50": 4.087,
      "p90": 6.434,
      "sd": 1.667,
      "separates": [
        "literary"
      ]
    },
    "commasPerSentence": {
      "p10": 0.4,
      "p50": 0.8,
      "p90": 1.35,
      "sd": 0.402,
      "separates": [
        "business-email",
        "literary"
      ]
    },
    "coordinationRate": {
      "p10": 1.087,
      "p50": 2.236,
      "p90": 3.473,
      "sd": 0.931,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "literary"
      ]
    },
    "figures": {
      "p10": 0,
      "p50": 0.4,
      "p90": 1,
      "sd": 0.427,
      "separates": [
        "literary"
      ]
    },
    "generic": {
      "p10": 0,
      "p50": 0.2,
      "p90": 0.6,
      "sd": 0.206,
      "separates": [
        "institutional"
      ]
    },
    "hardPer100": {
      "p10": 1.899,
      "p50": 4.549,
      "p90": 8.227,
      "sd": 2.655,
      "separates": [
        "explanatory"
      ]
    },
    "impersonalOpenerShare": {
      "p10": 0,
      "p50": 0,
      "p90": 0.1,
      "sd": 0.047,
      "separates": []
    },
    "names": {
      "p10": 0.6,
      "p50": 1.8,
      "p90": 3.4,
      "sd": 1.21,
      "separates": [
        "institutional"
      ]
    },
    "nominalisationRate": {
      "p10": 1.576,
      "p50": 3.222,
      "p90": 5.534,
      "sd": 1.6,
      "separates": [
        "business-email",
        "explanatory",
        "literary"
      ]
    },
    "participialRate": {
      "p10": 0,
      "p50": 0,
      "p90": 0.133,
      "sd": 0.062,
      "separates": []
    },
    "pronounOpenerShare": {
      "p10": 0.067,
      "p50": 0.213,
      "p90": 0.4,
      "sd": 0.136,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "literary"
      ]
    },
    "sentenceCv": {
      "p10": 0.275,
      "p50": 0.377,
      "p90": 0.52,
      "sd": 0.096,
      "separates": [
        "business-email",
        "institutional",
        "literary"
      ]
    },
    "skeletonRepeat": {
      "p10": 0,
      "p50": 0.031,
      "p90": 0.081,
      "sd": 0.038,
      "separates": []
    },
    "specificsPer100": {
      "p10": 2.54,
      "p50": 5.2,
      "p90": 9.18,
      "sd": 2.733,
      "separates": [
        "explanatory",
        "literary"
      ]
    },
    "tradePer100": {
      "p10": 0,
      "p50": 0.592,
      "p90": 1.515,
      "sd": 0.612,
      "separates": [
        "business-email",
        "explanatory",
        "institutional",
        "literary"
      ]
    },
    "tricolons": {
      "p10": 0,
      "p50": 0.4,
      "p90": 0.8,
      "sd": 0.309,
      "separates": [
        "business-email"
      ]
    }
  }
};
