import { describe, expect, it } from "vitest";
import { buildBriefing, BriefingBuildError, sectionOrder } from "../build";
import { sha256Hex } from "../hash";
import { lintBriefing, readableFields } from "../lint";
import type { ClientConfig, RawInput, SparseRawInput } from "../types";
import client01 from "./fixtures/all-clients/client-01.json";
import client02 from "./fixtures/all-clients/client-02.json";
import client03 from "./fixtures/all-clients/client-03.json";
import client04 from "./fixtures/all-clients/client-04.json";
import client05 from "./fixtures/all-clients/client-05.json";
import client06 from "./fixtures/all-clients/client-06.json";
import client07 from "./fixtures/all-clients/client-07.json";

// These retain the seven source payloads' metrics and entry counts. Identities,
// URLs, queries, personal notes and approval content are redacted. The hashes
// were generated by the unchanged builder at the branch's base commit.
const clients = [client01, client02, client03, client04, client05, client06, client07];

describe.each(clients)("$config.slug: the 11 October cycle", (source) => {
  const fixture = () => structuredClone(source) as unknown as { input: RawInput; config: ClientConfig; expectedHash: string; expected: typeof source.expected };

  it("retains the exact complete-input result, including flags, log and approval hashes", () => {
    const f = fixture();
    const result = buildBriefing(f.input, f.config);
    expect(sha256Hex(JSON.stringify(result))).toBe(f.expectedHash);
    expect(result.briefing.status).toBe(f.expected.status);
    expect(result.briefing.sections).toEqual(f.expected.sections);
    expect(result.briefing.health.search.state).toBe(f.expected.searchState);
    expect(result.briefing.health.uptime.failed).toBe(f.expected.failedChecks);
    expect(result.flags.map((flag) => flag.code)).toEqual(f.expected.flags);
    expect(result.log.entries).toHaveLength(f.input.entries.length);
    expect(lintBriefing(result.briefing)).toEqual([]);
  });

  it.each(["uptime", "search", "speed", "analytics"] as const)("omits unavailable %s without changing the other measured metrics", (sourceKey) => {
    const f = fixture();
    const complete = buildBriefing(f.input, f.config);
    const input: SparseRawInput = f.input;
    delete input[sourceKey];
    // The hand-written subhead must reflect the sources that are available.
    f.config.subhead = "";
    const { briefing, log, flags } = buildBriefing(input, f.config);
    const outputKey = sourceKey === "analytics" ? "visits" : sourceKey;
    expect(briefing.health).not.toHaveProperty(outputKey);
    for (const key of ["uptime", "search", "speed"] as const) {
      if (key !== sourceKey) expect(briefing.health[key]).toEqual(complete.briefing.health[key]);
    }
    if (sourceKey === "uptime") {
      expect(log.derivations.some((line) => line.startsWith("Uptime:"))).toBe(false);
      expect(flags.some((flag) => flag.code === "failed-checks")).toBe(false);
      expect(briefing.statusLabel).not.toBe("All good");
    }
    if (sourceKey === "search") {
      expect(log.excludedQueries).toEqual([]);
      expect(flags.some((flag) => flag.code === "excluded-query" || flag.code === "tracking-check")).toBe(false);
    }
    expect(lintBriefing(briefing)).toEqual([]);
  });

  it("drops the entire health section when all metric sources are absent", () => {
    const f = fixture();
    const { uptime: _uptime, search: _search, speed: _speed, analytics: _analytics, ...input } = f.input;
    f.config.subhead = "";
    const { briefing, log } = buildBriefing(input, f.config);
    expect(briefing.health).toEqual({});
    expect(briefing.sections).not.toContain("health");
    expect(briefing.statusLabel).toBe(f.config.approvals.length ? "3 things need you" : "Your update");
    expect(readableFields(briefing).filter(([key]) => key.startsWith("health."))).toEqual([]);
    expect(log.derivations).toEqual([]);
  });

  it("hides absent launch and approvals and does not invent a social section", () => {
    const f = fixture();
    delete f.config.launch;
    f.config.approvals = [];
    const { briefing } = buildBriefing(f.input, f.config);
    expect(briefing).not.toHaveProperty("launch");
    expect(briefing.approvals).toEqual([]);
    expect(briefing.sections).not.toContain("launch");
    expect(briefing.sections).not.toContain("needs-you");
    expect(briefing.sections).not.toContain("social");
    expect(briefing).not.toHaveProperty("social");
  });

  it.each(["headline", "note"] as const)("still requires the hand-written %s on sparse input", (key) => {
    const f = fixture();
    const { uptime: _uptime, search: _search, ...input } = f.input;
    f.config[key] = "  ";
    expect(() => buildBriefing(input, f.config)).toThrow(BriefingBuildError);
  });
});

describe("section compatibility", () => {
  it("retains the legacy section-decision call without a health field", () => {
    expect(sectionOrder({ approvals: [], changes: [], maintenanceCount: 0, moreChangesCount: 0 })).toEqual(["status", "health", "note"]);
  });

  it("omits health when fewer than five speed runs leave no usable metrics", () => {
    const f = structuredClone(client01) as unknown as { input: SparseRawInput; config: ClientConfig };
    delete f.input.uptime;
    delete f.input.search;
    delete f.input.analytics;
    f.input.speed!.runs = f.input.speed!.runs.slice(0, 4);
    f.config.subhead = "";
    const { briefing, flags } = buildBriefing(f.input, f.config);
    expect(briefing.health).toEqual({});
    expect(briefing.sections).not.toContain("health");
    expect(flags.some((flag) => flag.code === "speed-runs")).toBe(true);
  });
});
