// Regenerates test-vectors.json with node:crypto, deliberately NOT through the
// package, so the published vectors are an independent implementation of the
// protocol in docs/README. Run: node scripts/gen-vectors.mjs > test-vectors.json
import { createHash, createHmac } from "node:crypto";

const secretBytes = Buffer.from(Array.from({ length: 32 }, (_, i) => i));
const secret = secretBytes.toString("base64url");

function vector(name, p) {
  const bodySha256 = createHash("sha256").update(p.body, "utf8").digest("hex");
  const canonical = ["DD-SYNTH-V1", p.kid, p.ts, p.runId, p.mode, p.client, p.form, "POST", p.host, p.path, p.contentType, bodySha256].join("\n");
  const signature = createHmac("sha256", secretBytes).update(canonical, "utf8").digest("hex");
  return { name, ...p, bodySha256, canonical, signature, header: `v1=${signature}` };
}

function report(name, p) {
  const bodySha256 = createHash("sha256").update(p.body, "utf8").digest("hex");
  const canonical = ["DD-SYNTH-REPORT-V1", p.kid, p.ts, p.kind, p.client, p.form, bodySha256].join("\n");
  const signature = createHmac("sha256", secretBytes).update(canonical, "utf8").digest("hex");
  return { name, ...p, bodySha256, canonical, signature, header: `v1=${signature}` };
}

const out = {
  note: "Secret is the 32 bytes 0x00..0x1f. TEST ONLY: never use it anywhere real. Generated by scripts/gen-vectors.mjs with node:crypto.",
  secretBase64Url: secret,
  requests: [
    vector("probe, JSON", {
      kid: "test-2026-10",
      ts: 1790000000,
      runId: "abcdefghijklmnop",
      mode: "probe",
      client: "sensphere",
      form: "contact",
      host: "staging.sensphere.co.uk",
      path: "/api/contact",
      contentType: "application/json",
      body: '{"name":"DD Synthetic Check","email":"s-abcdefghijklmnop@canary.domandigital.co.uk","message":"Synthetic check. Please ignore."}',
    }),
    vector("full, form-urlencoded, host with port", {
      kid: "test-2026-10-next",
      ts: 1790000123,
      runId: "7654327zyxwvuts2",
      mode: "full",
      client: "rmp",
      form: "enquiry",
      host: "localhost:4321",
      path: "/forms/enquiry",
      contentType: "application/x-www-form-urlencoded",
      body: "name=DD+Synthetic+Check&email=u-7654327zyxwvuts2%40canary.domandigital.co.uk",
    }),
    vector("empty body, ts 0, content type with a parameter", {
      kid: "test-2026-10",
      ts: 0,
      runId: "aaaaaaaaaaaaaaaa",
      mode: "probe",
      client: "dd",
      form: "newsletter",
      host: "domandigital.co.uk",
      path: "/api/subscribe",
      contentType: "application/json; charset=utf-8",
      body: "",
    }),
  ],
  reports: [
    report("beacon, synthetic_rejected", {
      kid: "test-2026-10",
      ts: 1790000000,
      kind: "beacon",
      client: "sensphere",
      form: "contact",
      body: '{"v":1,"kind":"beacon","client":"sensphere","form":"contact","code":"synthetic_rejected","reason":"bad_signature"}',
    }),
  ],
};
console.log(JSON.stringify(out, null, 2));
