/**
 * Emit plain CSS custom properties.
 *
 * Plain custom properties, not a Tailwind theme and not a JS object, because the
 * consumers do not agree on a styling engine: the monorepo is on Tailwind v4,
 * one client site is on Tailwind v3, and another has no Tailwind at all. Custom
 * properties are the only output all three can read without a build step.
 */

import { DURATION_MS, EASE, EXIT_RATIO, SCALE, SPRING } from "../motion/tokens.js";
import { type FluidSpaceOptions, fluidSpace, sectionRhythm } from "../space/scale.js";
import { type FluidTypeOptions, fluidType } from "../type/scale.js";
import { typeFeatureTokens } from "../type/features.js";
import { type SemanticInput, type SemanticResult, semantic } from "../color/semantic.js";
import type { RampStep } from "../color/ramp.js";

export interface EmitCssOptions {
  /** Selector the block is written under. Defaults to `:root`. */
  selector?: string;
  /** Provenance comments, keyed by token name. */
  notes?: Record<string, string>;
  /** Indent for each declaration. Defaults to two spaces. */
  indent?: string;
}

/** Render a token map as one CSS rule, with notes as trailing comments. */
export function emitCss(
  tokens: Record<string, string>,
  options: EmitCssOptions = {},
): string {
  const selector = options.selector ?? ":root";
  const indent = options.indent ?? "  ";
  const notes = options.notes ?? {};

  const lines = Object.entries(tokens).map(([name, value]) => {
    const note = notes[name];
    return `${indent}${name}: ${value};${note ? ` /* ${note} */` : ""}`;
  });

  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

export interface CraftTokensInput extends SemanticInput {
  /** Selector for the emitted block. Defaults to `:root`. */
  selector?: string;
  /** Type scale options. Pass `pin` to reproduce a site's existing sizes exactly. */
  type?: FluidTypeOptions;
  /** Space scale options. */
  space?: FluidSpaceOptions;
  /** Section rhythm overrides. */
  section?: Parameters<typeof sectionRhythm>[0];
}

export interface CraftTokensResult {
  /** The stylesheet text, ready to write to a `.css` file. */
  css: string;
  /** Every token emitted, name to value. */
  tokens: Record<string, string>;
  report: SemanticResult["report"];
  ramps: { accent: Record<RampStep, string> };
}

/** Motion tokens are fixed house numbers, identical for every consumer. */
export function motionTokens(): Record<string, string> {
  const tokens: Record<string, string> = {};
  for (const [name, value] of Object.entries(EASE)) {
    tokens[`--craft-ease-${kebab(name)}`] = value;
  }
  for (const [name, ms] of Object.entries(DURATION_MS)) {
    tokens[`--craft-duration-${kebab(name)}`] = `${ms}ms`;
  }
  tokens["--craft-exit-ratio"] = String(EXIT_RATIO);
  tokens["--craft-scale-press"] = String(SCALE.press);
  tokens["--craft-scale-enter"] = String(SCALE.enter);
  tokens["--craft-spring-damping"] = String(SPRING.damping);
  tokens["--craft-spring-stiffness"] = String(SPRING.stiffness);
  return tokens;
}

function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (ch) => `-${ch.toLowerCase()}`);
}

/**
 * The whole emitted layer: colour derived from the caller's anchors, motion from
 * the house constants, and a contrast report the caller is expected to read.
 */
export function craftTokens(input: CraftTokensInput): CraftTokensResult {
  const derived = semantic(input);
  const tokens = {
    ...derived.tokens,
    ...motionTokens(),
    ...fluidType(input.type).tokens,
    ...typeFeatureTokens(),
    ...fluidSpace(input.space),
    ...sectionRhythm(input.section),
  };

  const header = [
    "/* Generated by @domandigital/craft. Do not edit by hand.",
    " * Anchors are supplied by the consuming repo; every other value is derived,",
    " * and every contrast-sensitive pair carries its measured ratio as a comment.",
    " */",
  ].join("\n");

  return {
    css: `${header}\n${emitCss(tokens, {
      selector: input.selector ?? ":root",
      notes: derived.notes,
    })}`,
    tokens,
    report: derived.report,
    ramps: { accent: derived.accentRamp },
  };
}
