#!/usr/bin/env node
// Dev-only: snapshot the slice of the schema.org vocabulary this package emits,
// so src/__tests__/vocab.test.ts can check every builder's output keys without
// a network call or a runtime dependency.
//
// Why a test and not types: TypeScript reports an unknown key written directly
// in an object literal, but not one inside a conditional spread
// (`...(x ? { locality } : {})`). Every address field here is built that way,
// which is how `locality` shipped instead of `addressLocality`.
//
// Usage: node scripts/snapshot-vocab.mjs [version]   (default: the pin below)
// Re-run it after adding a new @type to a builder, or to move the pin.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const VERSION = process.argv[2] ?? "30.1";
const BASE = `https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/${VERSION}`;
const OUT = join(dirname(fileURLToPath(import.meta.url)), "../src/__tests__/fixtures/schemaorg-vocab.json");

// Every @type a builder can emit, plus the ones the tests pass in through a
// parameter (buildOrganization's `types`, WebsiteInput.potentialAction.type and
// resultType). Supertypes are added automatically.
const EMITTED_TYPES = [
  "AdministrativeArea", "AggregateRating", "Answer", "Article", "Brand", "BreadcrumbList",
  "City", "CollectionPage", "Comment", "ContactPage", "ContactPoint",
  "EducationalOccupationalCredential", "Electrician", "EntryPoint", "FAQPage", "GeoCircle",
  "GeoCoordinates", "ItemList", "ListItem", "LocalBusiness", "Offer", "OfferCatalog",
  "OpeningHoursSpecification", "Organization", "Person", "Place", "PostalAddress", "Product",
  "PropertyValue", "Question", "Rating", "Reservation", "ReserveAction", "Review", "SearchAction",
  "Service", "SoftwareApplication", "SpeakableSpecification", "UnitPriceSpecification",
  "WebPage", "WebSite",
];

/** RFC 4180: quoted fields, doubled quotes, newlines inside quotes. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field); field = "";
      rows.push(row); row = [];
    } else field += c;
  }
  if (field !== "" || row.length > 0) { row.push(field); rows.push(row); }
  const [header, ...body] = rows.filter((r) => r.length > 1);
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""])));
}

const SCHEMA = /^https?:\/\/schema\.org\//;
const short = (iri) => iri.replace(SCHEMA, "");
// Cells can also name external vocabularies (an OMG Commons class appears as
// a supertype in 30.x). Only schema.org terms matter to a schema.org parser.
const list = (cell) =>
  cell.split(",").map((s) => s.trim()).filter((s) => SCHEMA.test(s)).map(short);

async function fetchCsv(kind) {
  const url = `${BASE}/schemaorg-current-https-${kind}.csv`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return parseCsv(await res.text());
}

const [typeRows, propRows] = await Promise.all([fetchCsv("types"), fetchCsv("properties")]);

const parentsOf = new Map(typeRows.map((r) => [short(r.id), list(r.subTypeOf)]));
const typeSupersededBy = new Map(typeRows.filter((r) => r.supersededBy).map((r) => [short(r.id), short(r.supersededBy)]));

const types = {};
const queue = [...EMITTED_TYPES];
while (queue.length > 0) {
  const t = queue.shift();
  if (t in types) continue;
  const parents = parentsOf.get(t);
  if (!parents) throw new Error(`schema.org ${VERSION} has no type "${t}"`);
  types[t] = parents;
  queue.push(...parents);
}

const properties = {};
const supersededBy = {};
for (const r of propRows) {
  const domains = list(r.domainIncludes).filter((d) => d in types);
  if (domains.length === 0) continue;
  const name = short(r.id);
  properties[name] = domains.sort();
  if (r.supersededBy) supersededBy[name] = list(r.supersededBy).join(", ");
}
for (const t of Object.keys(types)) {
  if (typeSupersededBy.has(t)) supersededBy[t] = typeSupersededBy.get(t);
}

const sortKeys = (o) => Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k]]));
const fixture = {
  schemaVersion: VERSION,
  source: `${BASE}/schemaorg-current-https-{types,properties}.csv`,
  note: "Generated by scripts/snapshot-vocab.mjs. Do not edit by hand.",
  types: sortKeys(types),
  properties: sortKeys(properties),
  supersededBy: sortKeys(supersededBy),
};
writeFileSync(OUT, `${JSON.stringify(fixture, null, 1)}\n`);
console.log(
  `schema.org ${VERSION}: ${Object.keys(types).length} types, ${Object.keys(properties).length} properties -> ${OUT}`,
);
